### ISSUE TITLE
User modifiable bridge address for configurator?

### ISSUE THREAD

**Issue by aptalca** [armzilla/amazon-echo-ha-bridge#11]
Hi arm,

Great work on this. I am thoroughly enjoying the echo controlling all of my automation devices.

I created a docker for this, and several people have been using it: https://registry.hub.docker.com/u/aptalca/docker-amazon-echo-ha-bridge/

But one issue is that, configurator.html has the bridge address hardcoded as localhost. Unfortunately in docker the bridge is unreachable through localhost (it should be as I'm using host mode, but can't figure out why it is not) and the local ip of the server needs to be used. It results in the CORS error being displayed, but the real issue is that localhost is not reachable (I tried disabling web security in chrome and that did not work either)

To test, I replaced localhost with the local server ip in configurator.html in the jar file and everything seems to work that way.

Is it possible to have the bridge address user selected/modified, or even extracted from the url?

Another idea is that, the docker requires the input of the local server ip so it can run java with the upnp.config.address=$SERVERIP parameter. $SERVERIP is passed into the docker container as an environment variable. Perhaps that could be used for the configurator.html?

I'm sure you'll have better ideas on how to get around it.

Thanks

**Comment by aptalca** [comment]
For now, I am using a very hacky way to get around the limitation.

Once the docker container starts, it replaces the "localhost" with $SERVERIP using sed in a separate configurator.html and then it updates the configurator.html within the jar file with the modified version before running java

It works, but it would require a lot of work every time there is a new release.

Thanks

**Comment by duanemay** [comment]
I submitted a pull request that fixes this, it uses the current address the page was loaded from. It also allows you to reload the devices if you have a different configuration.

See Pull request https://github.com/armzilla/amazon-echo-ha-bridge/pull/13

**Comment by aptalca** [comment]
Looks great :-) Thanks

Hopefully Arm will merge soon. I see that he hasn't been active on github lately

**Comment by armzilla** [comment]
merged #13.  Some folks are complaining that my documentation sucks (and it does).  Can someone improve the MD?
