### ISSUE TITLE
Echo Does Not Recognize More Than 26 Devices

### ISSUE THREAD

**Issue by ultrajones** [armzilla/amazon-echo-ha-bridge#12]
Hi, I am using the amazon-echo-ha-bridge on a Raspberry Pi 2 and absolutely love it.  However, whenever I attempt to add my 27th connected device, the Amazon Echo no longer sees any connected devices.  Any ideas how to troubleshoot this?

**Comment by okachobi** [comment]
Someone else mentioned on another report that there might be an Echo limit.

It would be interesting if amazon-echo-ha-bridge could support groups on its side.  The Echo supports groups, but then each light must be registered separately.  If there were a way to register an array of endpoints with amazon-echo-ha-bridge and give them one label and have it make the calls to all when the echo sends a command, then that might avoid the limit.

**Comment by ultrajones** [comment]
I worked around this limit but installing a second amazon-echo-ha-bridge on another Raspberry Pi 2.  I now have the Amazon echo controlling 48 connected devices.

**Comment by armzilla** [comment]
we can potentially emulate multiple number of hues to try to accommodate this issue

**Comment by yang3535** [comment]
I'm running into this as well.  Exactly as the OP has described it.  I have about 40 devices I'd like to get online.  Thanks for creating this capability!

**Comment by shanekuz** [comment]
Im having the same issue, im running on windows and have tried to launch a second bridge on the same box bound to another IP address but the java window opens and then closes after about 10 seconds.  Should i be able to launch two gateways on the same box or do i need to setup another?

**Comment by jlippold** [comment]
Make sure you change the upnp port to run multiple instances.

```
java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.110 --server.port=8081 --upnp.response.port=50001
```

**Comment by sipvoip** [comment]
I have 129 lights I would like to control, has there been any progress on doing it with one echo-bridge?

**Comment by shanekuz** [comment]
I have a number of bridges running on one Windows PC, you need to bind multiple IPs to the machine and ensure the upnp ports are different for each instance.  So you will need to run 5 or 6 instances that's all but it does work fine.

**Comment by jlippold** [comment]
You don't need multiple IP addresses. See my example in this pull req: https://github.com/armzilla/amazon-echo-ha-bridge/pull/56

**Comment by sipvoip** [comment]
Is there a plan to do this with one bridge? I think it would be a lot cleaner, I am willing to pay for the development work.

**Comment by armzilla** [comment]
Latest in develop will emulate multiple hue gateways by using multiple ports
