### ISSUE TITLE
Run as windows service?

### ISSUE THREAD

**Issue by megamalain** [armzilla/amazon-echo-ha-bridge#14]
Hi Arm,

Is there anyway to get echo bridge to run as a windows service?

**Comment by m19brandon** [comment]
This is what i am doing.
1. Create a batch file with the command java -Xms32m -Xmx128m -jar C:\amazon-echo-ha-bridge\amazon-echo-bridge-0.2.0.jar --upnp.config.address=192.168.1.1 --server.port=8080
2. Add the batch file to Windows Task to launch on startup.
