### ISSUE TITLE
Dim option

### ISSUE THREAD

**Issue by gravesjohnr** [armzilla/amazon-echo-ha-bridge#23]
This is a feature request more than issue...

The echo supports dim commands:
Alexa, dim the living room to 20%.

It would be fabulous to add this to the bridge.

According to the vera docs: http://wiki.micasaverde.com/index.php/Luup_Requests
Dim should be supported via web call:
http://ip_address:3480/data_request?id=action&output_format=json&DeviceNum=7&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&newLoadlevelTarget=30

**Comment by armzilla** [comment]
try this:
http://ip_address:3480/data_request?id=action&output_format=json&DeviceNum=7&serviceId=urn:upnp-org:serviceId:Dimming1&action=SetLoadLevelTarget&newLoadlevelTarget=${intensity.percent}

bridge will take the dim value and expand the expression.   I didnt document this very well and will use this issue to do so.

**Comment by armzilla** [comment]
${intensity.byte} can be used by targets that take 0-255
