### ISSUE TITLE
Not working with Harmony?

### ISSUE THREAD

**Issue by Nomar383** [armzilla/amazon-echo-ha-bridge#29]
I have the bridge setup as a docker on my unraid server. It has been working great with the echo, but I can't seem to get the Harmony Hub to see the bridge. Do you have to do something different to get the Harmony to work?

**Comment by adamtart** [comment]
The Bridge interacts with other services via RESTful requests. This means that you can make the bridge send an HTTP request (i.e., URL) to another service or device on your network -- for example, you can create a device in the Bridge called "Harmony" where triggering ON sends a request like http://192.168.1.42:8000/on and triggering OFF sends a request like http://192.168.1.42:8000/off.

Unfortunately, the Harmony Hub is not quite so simple: you cannot just send an HTTP request to it. Instead, you must authenticate to it using Logitech's authentication service and then interact with it through its own API (which follows an XML-like format).

The simplest thing to do would be to have three pieces to your set-up: (1) The Amazon Echo HA Bridge which sends HTTP requests to (2) a separate, simple HTTP server which accepts HTTP requests and performs more complicated logic, such as triggering commands on (3) a separate process which has all of the complexity of interacting with the Harmony Hub.  (Technically 2 and 3 can be the same service, if you're willing to write it yourself instead of stringing together already-written such services.)

For an example with detailed steps, you should check out Reddit user svideo's write up here: https://www.reddit.com/r/homeautomation/comments/377onm/extending_amazon_echo_voice_control_to_existing/

**Comment by Nomar383** [comment]
Thanks for taking the time to reply. I might have misunderstood the harmony
hub support. I have the echo->Bridge->Vera->Harmony working perfectly
actually.

I'm actually trying to use the home automation buttons on the harmony
remote. So Harmony->Bidge->Vera to turn lights on and off.

There is another project that emulates the hue bridge to accomplish this
and I thought the functionality might have been added here as well.

On Tuesday, August 25, 2015, Adam Tart <notifications@github.com> wrote:

> The Bridge interacts with other services via RESTful requests. This means
> that you can make the bridge send an HTTP request (i.e., URL) to another
> service or device on your network -- for example, you can create a device
> in the Bridge called "Harmony" where triggering ON sends a request like
> http://192.168.1.42:8000/on and triggering OFF sends a request like
> http://192.168.1.42:8000/off.
>
> Unfortunately, the Harmony Hub is not quite so simple: you cannot just
> send an HTTP request to it. Instead, you must authenticate to it using
> Logitech's authentication service and then interact with it through its own
> API (which follows an XML-like format).
>
> The simplest thing to do would be to have three pieces to your set-up: (1)
> The Amazon Echo HA Bridge which sends HTTP requests to (2) a separate,
> simple HTTP server which accepts HTTP requests and performs more
> complicated logic, such as triggering commands on (3) a separate process
> which has all of the complexity of interacting with the Harmony Hub.
> (Technically 2 and 3 can be the same service, if you're willing to write it
> yourself instead of stringing together already-written such services.)
>
> For an example with detailed steps, you should check out Reddit user
> svideo's write up here:
> https://www.reddit.com/r/homeautomation/comments/377onm/extending_amazon_echo_voice_control_to_existing/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armzilla/amazon-echo-ha-bridge/issues/29#issuecomment-134669036>
> .
>


-- 
-Kalen

**Comment by adamtart** [comment]
Ah, interesting. Mind if I ask (1) how did you get the
echo->bridge->vera->harmony chain working? I wonder if it would be better
to use Vera than my own unreliable middleware I wrote myself. And (2) what
is the other hue bridge emulator project? I'd be curious to check it out.
Thanks!

**Comment by Nomar383** [comment]
There is a harmony hub plugin for Vera. I just send commands to that plugin
like you would send a command to a light switch and I am able to start
activities and turn everything off.

This is the repo I was looking at that was specifically designed to work
with the harmony to take advantage of the remote buttons:
https://github.com/falk0069/hue-upnp

On Tuesday, August 25, 2015, Adam Tart <notifications@github.com> wrote:

> Ah, interesting. Mind if I ask (1) how did you get the
> echo->bridge->vera->harmony chain working? I wonder if it would be better
> to use Vera than my own unreliable middleware I wrote myself. And (2) what
> is the other hue bridge emulator project? I'd be curious to check it out.
> Thanks!
>
> On Tue, Aug 25, 2015 at 11:54 AM, Kalen Hansen <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Thanks for taking the time to reply. I might have misunderstood the
> harmony
> > hub support. I have the echo->Bridge->Vera->Harmony working perfectly
> > actually.
> >
> > I'm actually trying to use the home automation buttons on the harmony
> > remote. So Harmony->Bidge->Vera to turn lights on and off.
> >
> > There is another project that emulates the hue bridge to accomplish this
> > and I thought the functionality might have been added here as well.
> >
> > On Tuesday, August 25, 2015, Adam Tart <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > The Bridge interacts with other services via RESTful requests. This
> means
> > > that you can make the bridge send an HTTP request (i.e., URL) to
> another
> > > service or device on your network -- for example, you can create a
> device
> > > in the Bridge called "Harmony" where triggering ON sends a request like
> > > http://192.168.1.42:8000/on and triggering OFF sends a request like
> > > http://192.168.1.42:8000/off.
> > >
> > > Unfortunately, the Harmony Hub is not quite so simple: you cannot just
> > > send an HTTP request to it. Instead, you must authenticate to it using
> > > Logitech's authentication service and then interact with it through its
> > own
> > > API (which follows an XML-like format).
> > >
> > > The simplest thing to do would be to have three pieces to your set-up:
> > (1)
> > > The Amazon Echo HA Bridge which sends HTTP requests to (2) a separate,
> > > simple HTTP server which accepts HTTP requests and performs more
> > > complicated logic, such as triggering commands on (3) a separate
> process
> > > which has all of the complexity of interacting with the Harmony Hub.
> > > (Technically 2 and 3 can be the same service, if you're willing to
> write
> > it
> > > yourself instead of stringing together already-written such services.)
> > >
> > > For an example with detailed steps, you should check out Reddit user
> > > svideo's write up here:
> > >
> >
> https://www.reddit.com/r/homeautomation/comments/377onm/extending_amazon_echo_voice_control_to_existing/
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/armzilla/amazon-echo-ha-bridge/issues/29#issuecomment-134669036
> > >
> > > .
> > >
> >
> >
> > --
> > -Kalen
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/armzilla/amazon-echo-ha-bridge/issues/29#issuecomment-134700802
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/armzilla/amazon-echo-ha-bridge/issues/29#issuecomment-134718088>
> .
>


-- 
-Kalen

**Comment by Nomar383** [comment]
I actually used the previously linked repo to get the harmony remote buttons working, so I guess I'll just run 2 different hue emulators since they don't appear to conflict.
