### ISSUE TITLE
Dimming support

### ISSUE THREAD

**Issue by ifuchs** [armzilla/amazon-echo-ha-bridge#30]
I have an OnURL set to:
http://XXX/pantrylight.php?dim=${intensity.percent}
However, if I tell Alexa "dim pantry light to 50%", the Apache access.log shows:
GET /pantrylight.php?dim=20
Other intensities fail as well.
Running v0.2.1

**Comment by ifuchs** [comment]
I checked the Echo log and found that it seems to be Alexa that is having the problem understanding the percent value. For example, I say "90% and it shows 10%. Strange since I have not had other recognition problems.

**Comment by ifuchs** [comment]
I have found the dimming support to be essentially useless. More often than not it gets the values wrong. Has anyone had a better experience setting arbitrary values. For example is anyone using dimming support to control a thermostat which requires that the Echo precisely specify the dim level?

**Comment by audiofreak9** [comment]
For me, Alexa has been spot on with my requested dimming percentage.  I am using a custom 'echo.php' URL on an Apache server, on the same RPi as the bridge, to control my X10 lighting.  What does your 'pantrylight.php' control?

**Comment by audiofreak9** [comment]
Here is a post I remember reading where someone set specific dim levels for a Nest thermostat.  http://forum.micasaverde.com/index.php/topic,31920.msg241766/topicseen.html#msg241766

**Comment by ifuchs** [comment]
Unfortunately the Nest post only seems to reinforce my experience that the Echo is for some reason not getting the percentages correct which is why it was apparently necessary to have scenes defined for all the levels.  I can't attribute this to the bridge as it is clear in the Echo log that it is not recognizing the dim levels. I just don't know what to do about it. It makes the {intensity.percent} dimming feature rather useless.
