### ISSUE TITLE
Support Color Setting

### ISSUE THREAD

**Issue by shanekuz** [armzilla/amazon-echo-ha-bridge#40]
I'm assuming the Hue bulbs can along with brightness be configured to choose the color they are set at.  I'm using this gateway along with my home automation to turn on and off Mi Light bulbs and would like to be able to choose color.

Is there any plan to incorporate this?

**Comment by armzilla** [comment]
The echo itself does not send color information to the hue gateway unfortunately.

**Comment by ryanlaux** [comment]
Im thinking of getting milight bulbs and although I haven't bought any to mess with yet, theoretically I plan on creating color scenes for the milights that could be executed by some sort of controller/server on the raspberry pi, running at the same time as the amazon bridge. I'd make a few preset color "scenes", such as blue, orange, green etc.. and ask Alexa to "turn on Blue Mode" or something like that. Ideally I would just configure the echo bridge to send an http request to the second server running on the pi to get it all working

**Comment by shanekuz** [comment]
Yes that' works fine, I found "alex turn on the lounge lights red" didn't work so well as it doesn't pickup the red as I also have turn on the loung lights as a command so I has to go down turn on the lounge red lights and lounge blue lights.   But all worked fine in the end.  I used VoxCommando for mine with the bridge sending event requests to run the commands.

**Comment by ryanlaux** [comment]
Out of curiosity what server/code are you running as a bridge for the milights?

**Comment by shanekuz** [comment]
I'm running the amazon-echo-bridge-0.2.1 on windows on the same VMWare guest I run VoxCommando on.  I have had to have a second virtual machine running with another instance of the bridge running as you can only have 26odd commands on one bridge and I couldn't get two instances running on the same machine.
