### ISSUE TITLE
Dumb question... but where is the amazon-echo-ha-bridge jar file?

### ISSUE THREAD

**Issue by bklavet** [armzilla/amazon-echo-ha-bridge#42]
Came across this and would like to try it out, but I can't find the amazon-echo-ha-bride jar.  Where am I not looking?

Thanks for putting this out there!

Brian

**Comment by audiofreak9** [comment]
https://github.com/armzilla/amazon-echo-ha-bridge/releases

**Comment by bklavet** [comment]
Thank YOU!
