### ISSUE TITLE
Trouble Running on Raspberry Pi

### ISSUE THREAD

**Issue by spencerhooks** [armzilla/amazon-echo-ha-bridge#47]
This works great for me when I run it on my Mac, but when I run it on my Raspberry Pi I can't load the configurator. I get a white label error page, "This application has no explicit mapping for /error, so you are seeing this as a fallback." 

My Pi is model 2 running Raspian Jessie and Java 1.8.0. I'm running it with java -jar amazon-echo-bridge-*.jar.

Any recommendations for trouble shooting?

**Comment by Raptortail** [comment]
I am having the exact same issue.  I got it to work fine from my Windows 10 laptop but on my new Raspberry Pi 2 B with Java 1.8.0 and Raspian Jessie, I get the same message as spencerhooks.

Another interesting note is a message in the command output that says "c.armzilla.ha.upnp.UpnpSettingsResource : upnp device settings requested: amazon-ha-bridge from 192.168.1.124".  My Pi is running on an IP of 192.168.1.12, not 192.168.1.124.  I have triple checked the startup command for the bridge where I am clearly running "java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.12 --server.port=8081".  Not sure where the .124 is coming from.

Any help is appreciated.

**Comment by Raptortail** [comment]
Nevermind.  I'm an idiot.  I was trying to call "http://<ip>:8080" instead of "http://<ip>:8080/configurator.html"

**Comment by spencerhooks** [comment]
Idiot #2 here. At the risk of embarrassment, I will leave this here in case there are more of us.
