### ISSUE TITLE
Can't Discover: Echo integration using amazon echo ha bridge

### ISSUE THREAD

**Issue by SidShroff7** [armzilla/amazon-echo-ha-bridge#48]
I have amazon-echo-bridge running and can access the configurator http://IP.ip./configurator.html[1] and using postman send a raw json switch which shows up in the emulated bridge and the on / off test successfully.
But when i go to discover from Alexa, it won't find this hue device.
I've turned off Firewall, AV, Shut down my existing real hue bridge, removed all home devices, rebooted, switched bridge to run on port 80, exited EventGhost, but nothing seems to work.
SO CLOSE!!!
Some has to know or have some ideas??

**Comment by mlavelle42** [comment]
Try discover multiple times. I had the same problem and after 5 minutes, an
several "discover" tries, it worked. I didn't do anything at all - just
retried discover.


Michael R. Lavelle
317-224-9396

**Comment by SidShroff7** [comment]
TRY THIS

I uninstalled a WIndows 10 update that I noticed installed today and rebooted KB###? I don't know the number. It was a long shot and it seemed to work seriously! 

Install date was Nov 1. I don't know if it was that new KB or if I had to reboot again as I already did once and saw the 'windows update prompt'

I will have to install that KB later and try again later.
