### ISSUE TITLE
Echo not recognising devices I have added via the configurator page

### ISSUE THREAD

**Issue by litfoo** [armzilla/amazon-echo-ha-bridge#51]
I have managed to add a device on the Hue Bridge emulator configurator page and it has been assigned with an ID, has a name and is labelled as a Switch

However, when I ask Alexa to discover my devices, it does not pick it up. - Says it can't find any devices

Anyone have any ideas as to why it is not picking it up?

thanks,

litfoo

**Comment by paulwakeford** [comment]
I had the same issue until I started it with --upnp.config.address=  pointing to the server on which I was running the jar.

**Comment by litfoo** [comment]
Thanks for this paul - excuse my ignorance

on the box (xxx.xxx.x.80) i have the jar on , i am currently entering C:\echo>java -jar amazon-echo-bridge-o.2.1.jar to get the bridge running

where would I run/start with --upnp.config.address= exactly?

**Comment by paulwakeford** [comment]
C:\echo>java -jar amazon-echo-bridge-o.2.1.jar --upnp.config.address=xxx.xxx.x.80

For example I run mine on a server with IP 192.168.1.150 so I use 

java -jar amazon-echo-bridge-o.2.1.jar --upnp.config.address=192.168.1.150

**Comment by litfoo** [comment]
excellent news - used the command as you described paul and it found the device i had created

thanks again!

**Comment by litfoo** [comment]
how would one create a custom script/bat file for this command line to auto execute on startup of a PC? java -jar amazon-echo-bridge-o.2.1.jar --upnp.config.address=192.168.1.150

can it be entered as is or what would need in order to be able to auto-execute that command above?

thanks, litfoo

**Comment by jyarnell** [comment]
litfoo,
Here is what I use in a *.bat file that I run from the Task Scheduler:

cd C:\<path>
javaw -Xmx200m -jar -Djava.net.preferIPv4Stack=true amazon-echo-bridge-0.2.1.jar --upnp.config.address=<IP Address>

Cheers

**Comment by litfoo** [comment]
thanks for this - my patch is echo - so am wondering if i created a .bat file with:

cd C:\echo\ java -jar amazon-echo-bridge-o.2.1.jar --upnp.config.address=192.168.1.150

would that work? 

or do I need to specify the additional info you have mentioned?

thanks, litfoo

**Comment by litfoo** [comment]
not having much luck with the batch file - getting error: The system cannot find the path specified

my exact path that works from command line is:

C:\echo>java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.124 --server.port=8082

have tried the below in bat file but it does not execute- 

cd c:\echo\ java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.124 --server.port=8082

any ideas as to what I am doing wrong?

thanks, litfoo

**Comment by paulwakeford** [comment]
Just google 'batch file start up Windows' and follow one of the guides.

**Comment by litfoo** [comment]
trust me.. i have been googling that all day

**Comment by litfoo** [comment]
can anyone offer any more advice? I have been looking online but am still not getting very far

**Comment by ifuchs** [comment]
Try connecting your server directly to the access point serving the Echo and then see if Discovery works.

**Comment by litfoo** [comment]
thanks for the comment ifuchs - that problem is fixed now - Echo can discover my devices

the outstanding issue is the correct content for my .bat file

**Comment by paulwakeford** [comment]
cd c:\echo\ java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.124 --server.port=8082

This should be over two lines in your batch file.

cd c:\echo\ 

java -jar amazon-echo-bridge-0.2.1.jar --upnp.config.address=192.168.1.124 --server.port=8082

**Comment by litfoo** [comment]
Thanks again Paul. works like a charm
