### ISSUE TITLE
OSX support?

### ISSUE THREAD

**Issue by nckarm4** [armzilla/amazon-echo-ha-bridge#52]
I only own a mac OS X and was trying to do this on there however, when I open terminal and type "java -jar amazon-echo-bridge-0.2.1.jar" it just says unable to access jar file. does this have to be done on a PC?

**Comment by robwbartel** [comment]
I've had no problem running it on both a mini and a MBP, under Yosemite and El Capitan respectively. I'm assuming you were invoking this with the working directory set to where the jar file was located? If not then you would need to provide the path to the jar from whereever your terminal was (usually your home directory /Users/<you>)
