### ISSUE TITLE
How to disable UPNP?

### ISSUE THREAD

**Issue by attzonko** [armzilla/amazon-echo-ha-bridge#80]
I have tried giving the command line options:
--upnp.disable
--upnp.disable=true

Regardless in the log I see "Starting UPNP Discovery Listener". What am I doing wrong?

Thanks!

**Comment by shelzmike** [comment]
Did you ever figure this out. I am interested in this as well. Whenever I start the bridge, it constantly tries to discover devices from the various PC's on my network and it doesn't need to. I just want to manually add and remove devices without it running all of the unnecessary discovery.

**Comment by attzonko** [comment]
To be honest I am no longer using this tool. I switched to Home Assistant which had an integrated hue emulation component. 

As far as the UPNP I think my understanding of it was wrong.
