### ISSUE TITLE
Does this play nice with an existing Philips Hue Bridge?

### ISSUE THREAD

**Issue by robertvorthman** [armzilla/amazon-echo-ha-bridge#82]
I have Philips Hue lights that I plan to control with the Amazon Echo Dot I pre-ordered.  Will I be able to control amazon-echo-ha-bridge devices at the same time?  Or will Alexa have trouble when she sees two Philips Hue bridges?

**Comment by armzilla** [comment]
I have a physical hue bridge and the soft bridge active at the same time with no problem. From observation the echo uses your IP and port as the unique key for your discovered devices.  You should have no problem with multiple hue gateways.

p.s.  i love how we anthropomorphize the echo!
